language: go

matrix:
  include:
    - go: 1.13.x
      addons:
        postgresql: "10"
      dist: bionic
    - go: 1.13.x
      addons:
        postgresql: "10"
      dist: xenial
    - go: 1.13.x
      addons:
        postgresql: "9.6"
      dist: bionic
    - go: 1.13.x
      addons:
        postgresql: "9.6"
      dist: xenial
    - go: 1.13.x
      addons:
        postgresql: "9.5"
      dist: bionic
    - go: 1.13.x
      addons:
        postgresql: "9.5"
      dist: xenial
    - go: 1.12.x
      addons:
        postgresql: "9.5"
      dist: xenial
    - go: 1.11.x
      addons:
        postgresql: "9.5"
      dist: xenial
    - go: 1.10.x
      addons:
        postgresql: "9.5"
      dist: xenial
    - go: 1.9.x
      addons:
        postgresql: "9.5"
      dist: xenial

before_script:
  - psql --user postgres --command "CREATE TABLE test_filestore(name TEXT, modified BIGINT, meta JSONB, content BYTEA)"
  - psql --user postgres --command "ALTER  TABLE test_filestore ADD CONSTRAINT test_filestore_pkc PRIMARY KEY(name, modified)"

env:
  - PGUSER=postgres PGDATABASE=postgres

script: go test -cover
